### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/ChangelogManager#21]
Similar to DevOps task but for GH Actions

**Comment by DorijanH** [comment]
Please @AleksandarDev, can you create an empty public repository for this GitHub action?

For an example, *Report Generator* tool has a [repository](https://github.com/danielpalme/ReportGenerator) that contains the tool's source code and [Azure DevOps extension](https://github.com/danielpalme/ReportGenerator/tree/main/src/AzureDevopsTask) and a [repository](https://github.com/danielpalme/ReportGenerator-GitHub-Action) for GitHub Action

**Comment by AleksandarDev** [comment]
@DorijanH I created https://github.com/Enterwell/ChangelogManager-actions

**Comment by DorijanH** [comment]
@AleksandarDev Nice, thanks!
I'm just not sure about the plural naming sufix. Since that's a *single* action that can have multiple versions managed by the github releases.

**Comment by AleksandarDev** [comment]
@DorijanH Renamed to `...-Action`
