### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by drittuper** [Enterwell/ChangelogManager#25]
Unfortunately there's no support for VS2022, do have any plans on resolving that?

**Comment by AleksandarDev** [comment]
Support is added via this PR: https://github.com/Enterwell/ChangelogManager/pull/11

**Comment by AleksandarDev** [comment]
@drittuper New versions are published on Marketplace: https://marketplace.visualstudio.com/items?itemName=Enterwell.EnterwellChangelogVsix
