### ISSUE TITLE
Compilation of CHANGELOG.md

### ISSUE THREAD

**Issue by mariugul** [Enterwell/ChangelogManager#4]
Hi.

I have the extension in VS but I can't get the tool to compile the changes into a changelog.md. Do I need another tool like the CLI for this? It's seemingly hard to have to download and compile the project myself. Could you perhaps release the executables on GitHub?

Thanks.

**Comment by AleksandarDev** [comment]
@mariugul Thank you for your feedback. Please let us know if we can improve our documentation. 

We created [release 1.0.0](https://github.com/Enterwell/ChangelogManager/releases/tag/1.0.0) to help you get started using our tool. Link above contains pre-built binaries for Windows and Linux, as well as VS extension which is also available on VS Marketplace. 

For further instruction and example, see Readme.md files in each project.

**Comment by mariugul** [comment]
Thank you for releasing the files! However, I'm still confused how to compile the changes files into a CHANGELOG.MD. This doesn't seem clear in the documentation. Perhaps an example of this would be a good thing to add?

Anyway, this tools seems to have the potential to be really great!

**Comment by AleksandarDev** [comment]
@mariugul See updated readme files for more info. Let us know if it's still unclear how to use the `clm` tool to merge changes into changelog.md.

**Comment by AleksandarDev** [comment]
Stale, closing.
